server:
  port: 9000

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web.filter: TRACE
    es.in2: info

spring:
  application:
    name: VC Verifier
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/resources/

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

security:
  authorizationServer: "https://verifier.dome-marketplace-lcl.org"
  loginCode:
    expirationProperties:
      expiration: "5"
      cronUnit: "MINUTES"
  token:
    accessToken:
      expiration: "5"
      cronUnit: "MINUTES"

clientsRepository:
  uri: "https://raw.githubusercontent.com/rubenmodamioin2/dome-services-directory/refs/heads/main/trusted-service-list-lcl.yaml"

trustedIssuerList:
  uri: "http://localhost:8085/v4/issuers/"

crypto:
  privateKey: "73e509a7681d4a395b1ced75681c4dc4020dbab02da868512276dd766733d5b5" # for test purposes

verifier:
  ui:
    login:
      uris:
        onboardingUri:
        supportUri:
        walletUri: